# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-29 18:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_key', models.CharField(max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_emails', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('profile_color', models.CharField(default=b'#000', max_length=7)),
                ('profile_picture_raw', models.ImageField(blank=True, max_length=255, upload_to=b'media/profile-pictures/raw/%Y/%m/%d/')),
                ('profile_picture_160', models.ImageField(blank=True, max_length=255, upload_to=b'media/profile-pictures/160/%Y/%m/%d/')),
                ('profile_picture_250', models.ImageField(blank=True, max_length=255, upload_to=b'media/profile-pictures/250/%Y/%m/%d/')),
                ('profile_picture_500', models.ImageField(blank=True, max_length=255, upload_to=b'media/profile-pictures/500/%Y/%m/%d/')),
                ('role', models.CharField(blank=True, default=b'', max_length=255)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
